version: 2

jobs:
  jstests:
    docker:
      - image: node:10.16.0
    environment:
      TZ: "America/Chicago"
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run test-ci
  swiftlint:
    docker:
      - image: dantoml/swiftlint:latest
    steps:
      - checkout
      - run: swiftlint lint --reporter junit | tee result.xml
      - store_artifacts:
          path: result.xml
      - store_test_results:
          path: result.xml
  linux:
    docker:
      - image: codevapor/swift:5.0
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: vapor
          POSTGRES_DB: countdownclocks
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get update; apt-get install -y libssl-dev zlib1g-dev
      - run: swift build
      - run: swift test

  linux-release:
    docker:
      - image: codevapor/swift:5.0
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get update; apt-get install -y libssl-dev zlib1g-dev
      - run: swift build -c release

workflows:
  version: 2
  tests:
    jobs:
      - jstests
      - swiftlint
      - linux
      - linux-release

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - jstests
      - swiftlint
      - linux
      - linux-release
